server:
  port: 8086

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/simple-app-test
    username: postgres
    password: postgrespass
  jpa:
    show-sql: true
    properties:
      hibernate:
        format-sql: true

info:
  app:
    name: "MY_MVC_SHOP"

management:
  endpoints:
    web:
      exposure:
        include: "*"